/* eslint-disable prettier/prettier */
export const LOGIN_START="LOGIN_START"

export const LOAD_USERS_PROFILE="LOAD_USERS_PROFILE"
export const UPDATE_USERS_PROFILE="UPDATE_USERS_PROFILE"

export const LOAD_USERS_START="LOAD_USERS_START"
export const CREATE_USER_START="CREATE_USER_START"
export const DELETE_USER_START="DELETE_USER_START"
export const UPDATE_USER_START="UPDATE_USER_START"

export const LOAD_PROJECT_START="LOAD_PROJECT_START"
export const LOAD_PROJECT_START_FOR_ALL="LOAD_PROJECT_START_FOR_ALL"
export const CREATE_PROJECT_START="CREATE_PROJECT_START"
export const DELETE_PROJECT_START="DELETE_PROJECT_START"
export const UPDATE_PROJECT_START="UPDATE_PROJECT_START"


export const CHANGE_PASSWORD_START="CHANGE_PASSWORD_START"


export const GET_MANAGER_START="GET_MANAGER_START"
export const ASSIGN_MANAGER_START="ASSIGN_MANAGER_START"


export const GET_TEAM_LEAD_START="GET_TEAM_LEAD_START"
export const ASSIGN_TEAM_LEAD_START="ASSIGN_TEAM_LEAD_START"


export const GET_TEAM_MEMBER_START="GET_TEAM_MEMBER_START"
export const ASSIGN_TEAM_MEMBER_START="ASSIGN_TEAM_MEMBER_START"

export const GET_NOTIFICATION_START="GET_NOTIFICATION_START"


export const GET_LOGO_START="GET_LOGO_START"


