/* eslint-disable prettier/prettier */
export const LOGIN_START="LOGIN_START"
export const LOAD_USERS_PROFILE="LOAD_USERS_PROFILE"
export const LOAD_USERS_START="LOAD_USERS_START"
export const CREATE_USER_START="CREATE_USER_START"
export const DELETE_USER_START="DELETE_USER_START"
export const UPDATE_USER_START="UPDATE_USER_START"

export const LOAD_PROJECT_START="LOAD_PROJECT_START"
export const LOAD_PROJECT_START_FOR_ALL="LOAD_PROJECT_START_FOR_ALL"
export const CREATE_PROJECT_START="CREATE_PROJECT_START"
export const DELETE_PROJECT_START="DELETE_PROJECT_START"
export const UPDATE_PROJECT_START="UPDATE_PROJECT_START"
